
#This is an incomplete list. TODO - adapt from https://github.com/scrapinghub/dateparser/blob/master/dateparser/data/languages_info.py
country_2_lang = {   
    'aa': ['ar'],
    'ad': ['ca'],
    'ae': ['ar'],
    'af': ['fa', 'ps'],
    'ag': ['en'],
    'ai': ['en'],
    'al': ['sq'],
    'am': ['hy'],
    'ao': ['pt'],
    'ar': ['es'],
    'as': ['sm'],
    'at': ['de'],
    'au': ['en'],
    'aw': ['nl', 'pap'],
    'ax': ['sv'],
    'az': ['az'],
    'ba': ['hr', 'bs', 'sr'],
    'bb': ['en'],
    'bd': ['bn'],
    'be': ['de', 'nl', 'fr'],
    'bf': ['fr'],
    'bg': ['bg'],
    'bh': ['ar'],
    'bi': ['en', 'fr', 'rn'],
    'bj': ['fr'],
    'bl': ['fr'],
    'bm': ['en'],
    'bn': ['ms'],
    'bo': ['es', 'qu', 'ay'],
    'bq': ['nl'],
    'br': ['pt'],
    'bs': ['en'],
    'bt': ['dz'],
    'bw': ['en', 'tn'],
    'by': ['ru', 'be'],
    'bz': ['en'],
    'ca': ['en', 'fr'],
    'cd': ['fr'],
    'cf': ['sg', 'fr'],
    'cg': ['fr'],
    'ch': ['de', 'fr', 'it'],
    'ci': ['fr'],
    'ck': ['en'],
    'cl': ['es'],
    'cm': ['en', 'fr'],
    'cn': ['zh'],
    'co': ['es'],
    'cr': ['es'],
    'cu': ['es'],
    'cv': ['pt'],
    'cw': ['nl'],
    'cx': ['en'],
    'cy': ['tr', 'el'],
    'cz': ['cs'],
    'de': ['de'],
    'dj': ['ar', 'fr'],
    'dk': ['da'],
    'dm': ['en'],
    'do': ['es'],
    'dz': ['ar', 'fr'],
    'ec': ['es', 'qu'],
    'ee': ['et'],
    'eg': ['ar'],
    'eh': ['ar'],
    'er': ['en', 'ar'],
    'es': ['es'],
    'et': ['am'],
    'fi': ['fi', 'sv'],
    'fj': ['fj', 'en', 'hif'],
    'fk': ['en'],
    'fm': ['en'],
    'fo': ['fo'],
    'fr': ['fr'],
    'ga': ['fr'],
    'gb': ['en'],
    'gd': ['en'],
    'ge': ['ka'],
    'gf': ['fr'],
    'gg': ['en'],
    'gh': ['en'],
    'gi': ['en'],
    'gl': ['kl'],
    'gm': ['en'],
    'gn': ['fr'],
    'gp': ['fr'],
    'gq': ['pt', 'es', 'fr'],
    'gr': ['el'],
    'gt': ['es'],
    'gu': ['ch'],
    'gw': ['pt'],
    'gy': ['en'],
    'hk': ['zh', 'en'],
    'hn': ['es'],
    'hr': ['hr'],
    'ht': ['fr', 'ht'],
    'hu': ['hu'],
    'id': ['id'],
    'ie': ['en', 'ga'],
    'il': ['ar', 'he'],
    'im': ['en', 'gv'],
    'in': ['en', 'hi'],
    'io': ['en'],
    'iq': ['ar'],
    'ir': ['fa'],
    'is': ['is'],
    'it': ['it'],
    'je': ['en'],
    'jm': ['en'],
    'jo': ['ar'],
    'jp': ['ja'],
    'ke': ['en', 'sw'],
    'kg': ['ru', 'ky'],
    'kh': ['km'],
    'ki': ['en', 'gil'],
    'km': ['zdj', 'ar', 'fr', 'wni'],
    'kn': ['en'],
    'kp': ['ko'],
    'kr': ['ko'],
    'kw': ['ar'],
    'ky': ['en'],
    'kz': ['ru', 'kk'],
    'la': ['lo'],
    'lb': ['ar'],
    'lc': ['en'],
    'li': ['de'],
    'lk': ['ta', 'si'],
    'lr': ['en'],
    'ls': ['st', 'en'],
    'lt': ['lt'],
    'lu': ['de', 'lb', 'fr'],
    'lv': ['lv'],
    'ly': ['ar'],
    'ma': ['ar', 'tzm'],
    'mc': ['fr'],
    'md': ['ro'],
    'me': ['sr'],
    'mf': ['fr'],
    'mg': ['mg', 'en', 'fr'],
    'mh': ['en', 'mh'],
    'mk': ['mk'],
    'ml': ['fr'],
    'mm': ['my'],
    'mn': ['mn'],
    'mo': ['pt', 'zh'],
    'mq': ['fr'],
    'mr': ['ar'],
    'ms': ['en'],
    'mt': ['mt', 'en'],
    'mu': ['en', 'fr'],
    'mv': ['dv'],
    'mw': ['en', 'ny'],
    'mx': ['es'],
    'my': ['ms'],
    'mz': ['pt'],
    'na': ['en'],
    'nc': ['fr'],
    'ne': ['fr'],
    'nf': ['en'],
    'ng': ['en', 'yo'],
    'ni': ['es'],
    'nl': ['nl'],
    'no': ['nn', 'nb'],
    'np': ['ne'],
    'nr': ['na', 'en'],
    'nu': ['niu', 'en'],
    'nz': ['mi'],
    'om': ['ar'],
    'pa': ['es'],
    'pe': ['es', 'qu'],
    'pf': ['fr', 'ty'],
    'pg': ['tpi', 'ho', 'en'],
    'ph': ['fil', 'en'],
    'pk': ['en', 'ur'],
    'pl': ['pl'],
    'pm': ['fr'],
    'pn': ['en'],
    'pr': ['es'],
    'ps': ['ar'],
    'pt': ['pt'],
    'pw': ['en', 'pau'],
    'py': ['es', 'gn'],
    'qa': ['ar'],
    'qc': ['fr'],
    're': ['fr'],
    'ro': ['ro'],
    'rs': ['sr'],
    'ru': ['ru'],
    'rw': ['en', 'rw', 'fr'],
    'sa': ['ar'],
    'sb': ['en'],
    'sc': ['en', 'fr'],
    'sd': ['en', 'ar'],
    'se': ['sv'],
    'sg': ['zh', 'en', 'ta', 'ms'],
    'sh': ['en'],
    'si': ['sl'],
    'sj': ['nb'],
    'sk': ['sk'],
    'sl': ['en'],
    'sm': ['it'],
    'sn': ['fr'],
    'so': ['ar', 'so'],
    'sr': ['nl'],
    'ss': ['en'],
    'st': ['pt'],
    'sv': ['es'],
    'sx': ['en', 'nl'],
    'sy': ['ar', 'fr'],
    'sz': ['en', 'ss'],
    'tc': ['en'],
    'td': ['ar', 'fr'],
    'tg': ['fr'],
    'th': ['th'],
    'tj': ['tg'],
    'tk': ['tkl', 'en'],
    'tl': ['pt', 'tet'],
    'tm': ['tk'],
    'tn': ['ar', 'fr'],
    'to': ['en', 'to'],
    'tr': ['tr'],
    'tt': ['en'],
    'tv': ['tvl', 'en'],
    'tw': ['zh'],
    'tz': ['en', 'sw'],
    'ua': ['uk'],
    'ug': ['en', 'sw'],
    'us': ['en'],
    'uy': ['es'],
    'uz': ['uz'],
    'vc': ['en'],
    've': ['es'],
    'vg': ['en'],
    'vn': ['vi'],
    'vu': ['en', 'bi', 'fr'],
    'wf': ['fr'],
    'ws': ['en', 'sm'],
    'ye': ['ar'],
    'yt': ['fr'],
    'za': ['en'],
    'zm': ['en'],
    'zw': ['en', 'sn', 'nd']
    }

#TODO - get the complete list for our language
lang_2_country = {   
    'am': ['et'],
    'ar': [   
        'ae','iq','dz','eg','sd','aa','il','ps','sa','bh','km','dj','er','eh',
        'jo','kw','lb','ly','ma','mr','om','qa','so','sy','td','tn','ye'
        ],
    'ay': ['bo'],
    'az': ['az'],
    'be': ['by'],
    'bg': ['bg'],
    'bi': ['vu'],
    'bn': ['bd'],
    'bs': ['ba'],
    'ca': ['ad'],
    'ch': ['gu'],
    'cs': ['cz'],
    'da': ['dk'],
    'de': ['at', 'ch', 'de', 'be', 'li', 'lu'],
    'dv': ['mv'],
    'dz': ['bt'],
    'el': ['gr', 'cy'],
    'en': [  
        'pk','sd','au','ca','gb','gh','ie','in','us','ai','ag','bi','bs','bz',
        'bm','bb','bw','cm','ck','cx','ky','dm','er','fj','fk','fm','gg','gi',
        'gm','gd','gy','hk','im','io','jm','je','ke','ki','kn','lr','lc','ls',
        'mg','mh','mt','ms','mu','mw','na','nf','ng','nu','nr','pn','ph','pw',
        'pg','rw','sg','sh','sb','sl','ss','sz','sx','sc','tc','tk','to','tt',
        'tv','tz','ug','vc','vg','vu','ws','za','zm','zw'
        ],
    'es': [   
        'ar','es','mx','bo','cl','co','cr','cu','do','ec','gq','gt','hn','ni',
        'pa','pe','pr','py','sv','uy','ve'
        ],
    'et': ['ee'],
    'fa': ['ir', 'af'],
    'fi': ['fi'],
    'fil': ['ph'],
    'fj': ['fj'],
    'fo': ['fo'],
    'fr': [
        'dz', 'ca', 'ch', 'fr', 'qc', 'bi', 'be', 'bj', 'bf', 'bl', 'cf', 'ci',
        'cm', 'cd', 'cg', 'km', 'dj', 'ga', 'gn', 'gp', 'gq', 'gf', 'ht', 'lu', 
        'mf', 'mc', 'mg', 'ml', 'mq', 'mu', 'yt', 'nc', 'ne', 'pf', 're', 'rw', 
        'sn', 'pm', 'sc', 'sy', 'td', 'tg', 'tn', 'vu', 'wf'
    ],
    'ga': ['ie'],
    'gil': ['ki'],
    'gn': ['py'],
    'gv': ['im'],
    'he': ['il'],
    'hi': ['in'],
    'hif': ['fj'],
    'ho': ['pg'],
    'hr': ['hr', 'ba'],
    'ht': ['ht'],
    'hu': ['hu'],
    'hy': ['am'],
    'id': ['id'],
    'is': ['is'],
    'it': ['ch', 'it', 'sm'],
    'ja': ['jp'],
    'ka': ['ge'],
    'kk': ['kz'],
    'kl': ['gl'],
    'km': ['kh'],
    'ko': ['kr', 'kp'],
    'ky': ['kg'],
    'lb': ['lu'],
    'lo': ['la'],
    'lt': ['lt'],
    'lv': ['lv'],
    'mg': ['mg'],
    'mh': ['mh'],
    'mi': ['nz'],
    'mk': ['mk'],
    'mn': ['mn'],
    'ms': ['bn', 'my', 'sg'],
    'mt': ['mt'],
    'my': ['mm'],
    'na': ['nr'],
    'nb': ['no', 'sj'],
    'nd': ['zw'],
    'ne': ['np'],
    'niu': ['nu'],
    'nl': ['nl', 'aw', 'be', 'bq', 'cw', 'sr', 'sx'],
    'nn': ['no'],
    'ny': ['mw'],
    'pap': ['aw'],
    'pau': ['pw'],
    'pl': ['pl'],
    'ps': ['af'],
    'pt': ['br', 'pt', 'ao', 'cv', 'gw', 'gq', 'mo', 'mz', 'st', 'tl'],
    'qu': ['bo', 'ec', 'pe'],
    'rn': ['bi'],
    'ro': ['ro', 'md'],
    'ru': ['ru', 'by', 'kz', 'kg'],
    'rw': ['rw'],
    'sg': ['cf'],
    'si': ['lk'],
    'sk': ['sk'],
    'sl': ['si'],
    'sm': ['as', 'ws'],
    'sn': ['zw'],
    'so': ['so'],
    'sq': ['al'],
    'sr': ['ba', 'me', 'rs'],
    'ss': ['sz'],
    'st': ['ls'],
    'sv': ['fi', 'se', 'ax'],
    'sw': ['ke', 'tz', 'ug'],
    'ta': ['lk', 'sg'],
    'tet': ['tl'],
    'tg': ['tj'],
    'th': ['th'],
    'tk': ['tm'],
    'tkl': ['tk'],
    'tn': ['bw'],
    'to': ['to'],
    'tpi': ['pg'],
    'tr': ['tr', 'cy'],
    'tvl': ['tv'],
    'ty': ['pf'],
    'tzm': ['ma'],
    'uk': ['ua'],
    'ur': ['pk'],
    'uz': ['uz'],
    'vi': ['vn'],
    'wni': ['km'],
    'yo': ['ng'],
    'zdj': ['km'],
    'zh': ['cn', 'tw', 'hk', 'mo', 'sg']
    }
