default_label2label = {'SOC_ECO_CLASS': 'NORP',
                           'RACE': 'NORP',
                           'POLITICAL_PARTY': 'NORP',
                           'UNION': 'NORP',
                           'RELIGION': 'NORP',
                           'RELIGION_MEMBER': 'NORP',
                           'POLITICAL_PARTY_MEMBER': 'NORP',
                           'UNION_MEMBER': 'NORP',
                           'LANGUAGE': 'NORP',
                           'GPE': 'LOC',
                           'LOCATION': 'LOC',                           
                           'FAC': 'LOC',
                           'MEDICAL_SYMPTOM': 'DISEASE',
                           }

default_upper_ontology = {
        'PERSON': ['PERSON'],
        'PUBLIC_FIGURE': ['PUBLIC_FIGURE', 'PERSON'],
        'ORG': ['ORG'],
        'NORP': ['NORP', 'ORG'],
        'AGE': ['AGE'],
        'DISEASE': ['DISEASE'],
        'ADDRESS': ['ADDRESS', 'LOC'],
        'USER': ['USER'],
        'URL': ['URL'],
        'ID': ['ID'],
        'LICENSE_PLATE': ['LICENSE_PLATE', 'ID'],
        'PHONE': ['PHONE', 'ID',],
        'IP_ADDRESS': ['IP_ADDRESS', 'ID',],
        'ANIMAL': ['ANIMAL'],
        'FOOD' : ['FOOD'],
        'PLANT': ['PLANT'],
        'GENDER': ['GENDER'],
        'JOB': ['JOB'],
        'EVENT': ['EVENT'],
        'BIO_CHEM_ENTITY': ['BIO_CHEM_ENTITY'],
        'MEDICAL_THERAPY': ['MEDICAL_THERAPY'],
        'LAW': ['LAW'],
        'ANAT': ['ANAT'],
        'QUANTITY': ['QUANTITY'],
        'DATE': ['DATE'],
        'TIME': ['TIME'],
        'PRODUCT': ['PRODUCT'],
        'MISC': ['MISC'],
        'OTHER': ['OTHER'],
    }
